[
  {
    "prompt": "Union of a 45x40x9 box and a 18x18x5 box translated by (10, 17, 9)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(45, 40, 9).union(cq.Workplane('XY').box(18, 18, 5).translate((10, 17, 9)))"
  },
  {
    "prompt": "Two cubes: side 16 at origin and side 19 at (45, 28)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(16, 16, 16)\nbox2 = cq.Workplane('XY').box(19, 19, 19).translate((45, 28, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Two boxes, one 26x38x27 at origin, another 14x9x8 at (32,50,27)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(26, 38, 27)\nbox2 = cq.Workplane('XY').box(14, 9, 8).translate((32, 50, 27))\nresult = box1.union(box2)"
  },
  {
    "prompt": "A base box 40x12x13 with a smaller box 19x18x14 on top",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(40, 12, 13).faces('>Z').workplane().box(19, 18, 14)"
  },
  {
    "prompt": "A base box 41x41x7 with a smaller box 6x16x8 on top",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(41, 41, 7).faces('>Z').workplane().box(6, 16, 8)"
  },
  {
    "prompt": "Union of a 11x34x23 box and a 9x15x18 box translated by (48, 37, 23)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(11, 34, 23).union(cq.Workplane('XY').box(9, 15, 18).translate((48, 37, 23)))"
  },
  {
    "prompt": "A base box 40x37x12 with a smaller box 18x13x14 on top",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(40, 37, 12).faces('>Z').workplane().box(18, 13, 14)"
  },
  {
    "prompt": "Create a cube of side 30 and place a box 15x7x13 next to it at x=25",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(30, 30, 30)\nbox2 = cq.Workplane('XY').box(15, 7, 13).translate((25, 0, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Two cubes: side 24 at origin and side 5 at (36, 32)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(24, 24, 24)\nbox2 = cq.Workplane('XY').box(5, 5, 5).translate((36, 32, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Two cubes: side 40 at origin and side 5 at (15, 14)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(40, 40, 40)\nbox2 = cq.Workplane('XY').box(5, 5, 5).translate((15, 14, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Create a cube of side 37 and place a box 20x18x10 next to it at x=26",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(37, 37, 37)\nbox2 = cq.Workplane('XY').box(20, 18, 10).translate((26, 0, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Two cubes: side 26 at origin and side 19 at (14, 50)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(26, 26, 26)\nbox2 = cq.Workplane('XY').box(19, 19, 19).translate((14, 50, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Create a cube of side 29 and place a box 11x18x13 next to it at x=15",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(29, 29, 29)\nbox2 = cq.Workplane('XY').box(11, 18, 13).translate((15, 0, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Create a cube of side 35 and place a box 12x18x16 next to it at x=43",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(35, 35, 35)\nbox2 = cq.Workplane('XY').box(12, 18, 16).translate((43, 0, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "A base box 25x31x26 with a smaller box 17x11x19 on top",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(25, 31, 26).faces('>Z').workplane().box(17, 11, 19)"
  },
  {
    "prompt": "A base box 40x35x25 with a smaller box 10x17x5 on top",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(40, 35, 25).faces('>Z').workplane().box(10, 17, 5)"
  },
  {
    "prompt": "Union of a 14x40x26 box and a 6x6x12 box translated by (14, 43, 26)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(14, 40, 26).union(cq.Workplane('XY').box(6, 6, 12).translate((14, 43, 26)))"
  },
  {
    "prompt": "Union of a 35x28x30 box and a 13x5x12 box translated by (31, 24, 30)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(35, 28, 30).union(cq.Workplane('XY').box(13, 5, 12).translate((31, 24, 30)))"
  },
  {
    "prompt": "Two cubes: side 32 at origin and side 7 at (38, 42)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(32, 32, 32)\nbox2 = cq.Workplane('XY').box(7, 7, 7).translate((38, 42, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Two boxes, one 49x13x27 at origin, another 20x19x17 at (31,41,27)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(49, 13, 27)\nbox2 = cq.Workplane('XY').box(20, 19, 17).translate((31, 41, 27))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Union of a 16x45x24 box and a 11x13x15 box translated by (37, 43, 24)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(16, 45, 24).union(cq.Workplane('XY').box(11, 13, 15).translate((37, 43, 24)))"
  },
  {
    "prompt": "Create a cube of side 29 and place a box 13x10x14 next to it at x=41",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(29, 29, 29)\nbox2 = cq.Workplane('XY').box(13, 10, 14).translate((41, 0, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Two cubes: side 18 at origin and side 13 at (21, 28)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(18, 18, 18)\nbox2 = cq.Workplane('XY').box(13, 13, 13).translate((21, 28, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "A base box 11x49x5 with a smaller box 8x19x15 on top",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(11, 49, 5).faces('>Z').workplane().box(8, 19, 15)"
  },
  {
    "prompt": "Union of a 13x21x18 box and a 19x8x20 box translated by (33, 31, 18)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(13, 21, 18).union(cq.Workplane('XY').box(19, 8, 20).translate((33, 31, 18)))"
  },
  {
    "prompt": "A base box 49x31x10 with a smaller box 5x11x12 on top",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(49, 31, 10).faces('>Z').workplane().box(5, 11, 12)"
  },
  {
    "prompt": "Two boxes, one 32x24x14 at origin, another 12x11x13 at (15,46,14)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(32, 24, 14)\nbox2 = cq.Workplane('XY').box(12, 11, 13).translate((15, 46, 14))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Union of a 37x24x28 box and a 6x12x18 box translated by (41, 33, 28)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(37, 24, 28).union(cq.Workplane('XY').box(6, 12, 18).translate((41, 33, 28)))"
  },
  {
    "prompt": "Two cubes: side 16 at origin and side 19 at (20, 47)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(16, 16, 16)\nbox2 = cq.Workplane('XY').box(19, 19, 19).translate((20, 47, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Two cubes: side 27 at origin and side 13 at (19, 28)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(27, 27, 27)\nbox2 = cq.Workplane('XY').box(13, 13, 13).translate((19, 28, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Create a cube of side 15 and place a box 5x14x14 next to it at x=33",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(15, 15, 15)\nbox2 = cq.Workplane('XY').box(5, 14, 14).translate((33, 0, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Two cubes: side 36 at origin and side 18 at (25, 36)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(36, 36, 36)\nbox2 = cq.Workplane('XY').box(18, 18, 18).translate((25, 36, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Create a cube of side 37 and place a box 10x10x20 next to it at x=41",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(37, 37, 37)\nbox2 = cq.Workplane('XY').box(10, 10, 20).translate((41, 0, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "A base box 22x12x20 with a smaller box 7x12x10 on top",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(22, 12, 20).faces('>Z').workplane().box(7, 12, 10)"
  },
  {
    "prompt": "Two cubes: side 26 at origin and side 19 at (33, 11)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(26, 26, 26)\nbox2 = cq.Workplane('XY').box(19, 19, 19).translate((33, 11, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "A base box 11x35x6 with a smaller box 17x15x17 on top",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(11, 35, 6).faces('>Z').workplane().box(17, 15, 17)"
  },
  {
    "prompt": "Two cubes: side 33 at origin and side 17 at (10, 30)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(33, 33, 33)\nbox2 = cq.Workplane('XY').box(17, 17, 17).translate((10, 30, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "A base box 39x42x27 with a smaller box 14x8x12 on top",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(39, 42, 27).faces('>Z').workplane().box(14, 8, 12)"
  },
  {
    "prompt": "Create a cube of side 13 and place a box 14x18x6 next to it at x=27",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(13, 13, 13)\nbox2 = cq.Workplane('XY').box(14, 18, 6).translate((27, 0, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Union of a 49x39x10 box and a 6x7x5 box translated by (36, 27, 10)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(49, 39, 10).union(cq.Workplane('XY').box(6, 7, 5).translate((36, 27, 10)))"
  },
  {
    "prompt": "Create a cube of side 19 and place a box 6x10x13 next to it at x=39",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(19, 19, 19)\nbox2 = cq.Workplane('XY').box(6, 10, 13).translate((39, 0, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "A base box 29x26x25 with a smaller box 9x12x17 on top",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(29, 26, 25).faces('>Z').workplane().box(9, 12, 17)"
  },
  {
    "prompt": "Two boxes, one 33x22x11 at origin, another 17x19x18 at (28,14,11)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(33, 22, 11)\nbox2 = cq.Workplane('XY').box(17, 19, 18).translate((28, 14, 11))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Two boxes, one 17x42x26 at origin, another 17x10x10 at (49,14,26)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(17, 42, 26)\nbox2 = cq.Workplane('XY').box(17, 10, 10).translate((49, 14, 26))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Two cubes: side 37 at origin and side 20 at (17, 16)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(37, 37, 37)\nbox2 = cq.Workplane('XY').box(20, 20, 20).translate((17, 16, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Two cubes: side 30 at origin and side 11 at (50, 42)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(30, 30, 30)\nbox2 = cq.Workplane('XY').box(11, 11, 11).translate((50, 42, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "A base box 31x27x27 with a smaller box 20x18x11 on top",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(31, 27, 27).faces('>Z').workplane().box(20, 18, 11)"
  },
  {
    "prompt": "Two cubes: side 39 at origin and side 15 at (17, 14)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(39, 39, 39)\nbox2 = cq.Workplane('XY').box(15, 15, 15).translate((17, 14, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Union of a 28x45x9 box and a 13x9x20 box translated by (18, 47, 9)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(28, 45, 9).union(cq.Workplane('XY').box(13, 9, 20).translate((18, 47, 9)))"
  },
  {
    "prompt": "A base box 34x14x5 with a smaller box 13x19x5 on top",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(34, 14, 5).faces('>Z').workplane().box(13, 19, 5)"
  },
  {
    "prompt": "Union of a 50x16x14 box and a 15x16x12 box translated by (49, 43, 14)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(50, 16, 14).union(cq.Workplane('XY').box(15, 16, 12).translate((49, 43, 14)))"
  },
  {
    "prompt": "Two boxes, one 30x27x9 at origin, another 18x11x6 at (28,46,9)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(30, 27, 9)\nbox2 = cq.Workplane('XY').box(18, 11, 6).translate((28, 46, 9))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Union of a 28x35x9 box and a 18x5x5 box translated by (23, 48, 9)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(28, 35, 9).union(cq.Workplane('XY').box(18, 5, 5).translate((23, 48, 9)))"
  },
  {
    "prompt": "Union of a 14x31x25 box and a 20x7x19 box translated by (46, 19, 25)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(14, 31, 25).union(cq.Workplane('XY').box(20, 7, 19).translate((46, 19, 25)))"
  },
  {
    "prompt": "Create a cube of side 21 and place a box 8x13x18 next to it at x=33",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(21, 21, 21)\nbox2 = cq.Workplane('XY').box(8, 13, 18).translate((33, 0, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "A base box 14x31x29 with a smaller box 6x19x8 on top",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(14, 31, 29).faces('>Z').workplane().box(6, 19, 8)"
  },
  {
    "prompt": "Two boxes, one 36x16x25 at origin, another 11x6x5 at (47,42,25)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(36, 16, 25)\nbox2 = cq.Workplane('XY').box(11, 6, 5).translate((47, 42, 25))\nresult = box1.union(box2)"
  },
  {
    "prompt": "A base box 39x36x25 with a smaller box 7x8x17 on top",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(39, 36, 25).faces('>Z').workplane().box(7, 8, 17)"
  },
  {
    "prompt": "Create a cube of side 33 and place a box 8x10x8 next to it at x=30",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(33, 33, 33)\nbox2 = cq.Workplane('XY').box(8, 10, 8).translate((30, 0, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Two boxes, one 31x13x23 at origin, another 11x14x8 at (23,23,23)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(31, 13, 23)\nbox2 = cq.Workplane('XY').box(11, 14, 8).translate((23, 23, 23))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Two boxes, one 15x48x28 at origin, another 18x18x8 at (50,38,28)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(15, 48, 28)\nbox2 = cq.Workplane('XY').box(18, 18, 8).translate((50, 38, 28))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Union of a 30x41x17 box and a 10x7x10 box translated by (30, 14, 17)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(30, 41, 17).union(cq.Workplane('XY').box(10, 7, 10).translate((30, 14, 17)))"
  },
  {
    "prompt": "Union of a 13x27x27 box and a 19x18x10 box translated by (49, 15, 27)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(13, 27, 27).union(cq.Workplane('XY').box(19, 18, 10).translate((49, 15, 27)))"
  },
  {
    "prompt": "Create a cube of side 39 and place a box 17x8x10 next to it at x=47",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(39, 39, 39)\nbox2 = cq.Workplane('XY').box(17, 8, 10).translate((47, 0, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Union of a 15x17x24 box and a 7x18x6 box translated by (27, 50, 24)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(15, 17, 24).union(cq.Workplane('XY').box(7, 18, 6).translate((27, 50, 24)))"
  },
  {
    "prompt": "Union of a 38x48x8 box and a 13x13x15 box translated by (12, 10, 8)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(38, 48, 8).union(cq.Workplane('XY').box(13, 13, 15).translate((12, 10, 8)))"
  },
  {
    "prompt": "Two cubes: side 21 at origin and side 15 at (30, 16)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(21, 21, 21)\nbox2 = cq.Workplane('XY').box(15, 15, 15).translate((30, 16, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "A base box 33x23x22 with a smaller box 16x7x20 on top",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(33, 23, 22).faces('>Z').workplane().box(16, 7, 20)"
  },
  {
    "prompt": "Two cubes: side 20 at origin and side 16 at (27, 11)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(20, 20, 20)\nbox2 = cq.Workplane('XY').box(16, 16, 16).translate((27, 11, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Two boxes, one 11x50x20 at origin, another 17x13x17 at (18,44,20)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(11, 50, 20)\nbox2 = cq.Workplane('XY').box(17, 13, 17).translate((18, 44, 20))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Union of a 27x34x22 box and a 19x11x15 box translated by (46, 26, 22)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(27, 34, 22).union(cq.Workplane('XY').box(19, 11, 15).translate((46, 26, 22)))"
  },
  {
    "prompt": "Two boxes, one 44x38x22 at origin, another 17x20x5 at (50,12,22)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(44, 38, 22)\nbox2 = cq.Workplane('XY').box(17, 20, 5).translate((50, 12, 22))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Union of a 41x34x20 box and a 8x5x14 box translated by (42, 12, 20)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(41, 34, 20).union(cq.Workplane('XY').box(8, 5, 14).translate((42, 12, 20)))"
  },
  {
    "prompt": "Union of a 15x50x24 box and a 11x7x9 box translated by (37, 46, 24)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(15, 50, 24).union(cq.Workplane('XY').box(11, 7, 9).translate((37, 46, 24)))"
  },
  {
    "prompt": "Union of a 34x46x25 box and a 9x7x10 box translated by (40, 30, 25)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(34, 46, 25).union(cq.Workplane('XY').box(9, 7, 10).translate((40, 30, 25)))"
  },
  {
    "prompt": "A base box 24x27x26 with a smaller box 18x13x14 on top",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(24, 27, 26).faces('>Z').workplane().box(18, 13, 14)"
  },
  {
    "prompt": "Create a cube of side 23 and place a box 8x16x6 next to it at x=10",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(23, 23, 23)\nbox2 = cq.Workplane('XY').box(8, 16, 6).translate((10, 0, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Two boxes, one 26x44x7 at origin, another 12x15x8 at (19,25,7)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(26, 44, 7)\nbox2 = cq.Workplane('XY').box(12, 15, 8).translate((19, 25, 7))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Two cubes: side 17 at origin and side 17 at (29, 50)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(17, 17, 17)\nbox2 = cq.Workplane('XY').box(17, 17, 17).translate((29, 50, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "A base box 47x30x29 with a smaller box 15x19x15 on top",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(47, 30, 29).faces('>Z').workplane().box(15, 19, 15)"
  },
  {
    "prompt": "Union of a 26x17x8 box and a 20x5x19 box translated by (26, 42, 8)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(26, 17, 8).union(cq.Workplane('XY').box(20, 5, 19).translate((26, 42, 8)))"
  },
  {
    "prompt": "Union of a 39x50x10 box and a 8x17x14 box translated by (39, 10, 10)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(39, 50, 10).union(cq.Workplane('XY').box(8, 17, 14).translate((39, 10, 10)))"
  },
  {
    "prompt": "Union of a 35x36x18 box and a 9x13x20 box translated by (43, 23, 18)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(35, 36, 18).union(cq.Workplane('XY').box(9, 13, 20).translate((43, 23, 18)))"
  },
  {
    "prompt": "Two cubes: side 19 at origin and side 13 at (12, 26)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(19, 19, 19)\nbox2 = cq.Workplane('XY').box(13, 13, 13).translate((12, 26, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Union of a 20x31x22 box and a 20x12x7 box translated by (28, 42, 22)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(20, 31, 22).union(cq.Workplane('XY').box(20, 12, 7).translate((28, 42, 22)))"
  },
  {
    "prompt": "A base box 41x10x18 with a smaller box 5x7x10 on top",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(41, 10, 18).faces('>Z').workplane().box(5, 7, 10)"
  },
  {
    "prompt": "Two cubes: side 15 at origin and side 14 at (48, 23)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(15, 15, 15)\nbox2 = cq.Workplane('XY').box(14, 14, 14).translate((48, 23, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Union of a 15x15x14 box and a 19x10x19 box translated by (24, 11, 14)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(15, 15, 14).union(cq.Workplane('XY').box(19, 10, 19).translate((24, 11, 14)))"
  },
  {
    "prompt": "Two cubes: side 11 at origin and side 12 at (31, 25)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(11, 11, 11)\nbox2 = cq.Workplane('XY').box(12, 12, 12).translate((31, 25, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Create a cube of side 34 and place a box 16x12x6 next to it at x=38",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(34, 34, 34)\nbox2 = cq.Workplane('XY').box(16, 12, 6).translate((38, 0, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Union of a 20x30x15 box and a 19x19x19 box translated by (47, 43, 15)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(20, 30, 15).union(cq.Workplane('XY').box(19, 19, 19).translate((47, 43, 15)))"
  },
  {
    "prompt": "Two cubes: side 19 at origin and side 9 at (50, 17)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(19, 19, 19)\nbox2 = cq.Workplane('XY').box(9, 9, 9).translate((50, 17, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "A base box 29x28x7 with a smaller box 11x17x15 on top",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(29, 28, 7).faces('>Z').workplane().box(11, 17, 15)"
  },
  {
    "prompt": "Create a cube of side 11 and place a box 10x20x17 next to it at x=31",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(11, 11, 11)\nbox2 = cq.Workplane('XY').box(10, 20, 17).translate((31, 0, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Two cubes: side 13 at origin and side 18 at (28, 14)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(13, 13, 13)\nbox2 = cq.Workplane('XY').box(18, 18, 18).translate((28, 14, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Two boxes, one 30x34x13 at origin, another 12x8x14 at (10,18,13)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(30, 34, 13)\nbox2 = cq.Workplane('XY').box(12, 8, 14).translate((10, 18, 13))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Create a cube of side 25 and place a box 8x16x6 next to it at x=44",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(25, 25, 25)\nbox2 = cq.Workplane('XY').box(8, 16, 6).translate((44, 0, 0))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Union of a 15x41x11 box and a 19x6x16 box translated by (20, 13, 11)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(15, 41, 11).union(cq.Workplane('XY').box(19, 6, 16).translate((20, 13, 11)))"
  },
  {
    "prompt": "A base box 50x22x26 with a smaller box 18x7x9 on top",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').box(50, 22, 26).faces('>Z').workplane().box(18, 7, 9)"
  },
  {
    "prompt": "Two boxes, one 18x28x21 at origin, another 7x7x20 at (37,46,21)",
    "code": "import cadquery as cq\nbox1 = cq.Workplane('XY').box(18, 28, 21)\nbox2 = cq.Workplane('XY').box(7, 7, 20).translate((37, 46, 21))\nresult = box1.union(box2)"
  },
  {
    "prompt": "Cylinder with diameter 9 and height 11",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(4.5).extrude(11)"
  },
  {
    "prompt": "Cylinder dia 31, height 49, positioned at (19, 29)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(15.5).extrude(49).translate((19, 29, 0))"
  },
  {
    "prompt": "A 66mm tall cylinder with radius 16.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(16.5).extrude(66)"
  },
  {
    "prompt": "Cylinder dia 14, height 19, positioned at (-46, 17)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(7.0).extrude(19).translate((-46, 17, 0))"
  },
  {
    "prompt": "A 84mm tall cylinder with radius 18.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(18.5).extrude(84)"
  },
  {
    "prompt": "Cylinder with diameter 19 and height 99",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(9.5).extrude(99)"
  },
  {
    "prompt": "Cylinder dia 28, height 16, positioned at (25, 12)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(14.0).extrude(16).translate((25, 12, 0))"
  },
  {
    "prompt": "Cylinder with diameter 44 and height 69",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(22.0).extrude(69)"
  },
  {
    "prompt": "Cylinder with diameter 30 and height 78",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(15.0).extrude(78)"
  },
  {
    "prompt": "Cylinder dia 47, height 52, positioned at (-11, -3)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(23.5).extrude(52).translate((-11, -3, 0))"
  },
  {
    "prompt": "Create a simple cylinder r=14.5 h=72",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(14.5).extrude(72)"
  },
  {
    "prompt": "Cylinder with diameter 35 and height 86",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(17.5).extrude(86)"
  },
  {
    "prompt": "Create a simple cylinder r=7.5 h=28",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(7.5).extrude(28)"
  },
  {
    "prompt": "Vertical rod diameter 14 length 21",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(7.0).extrude(21)"
  },
  {
    "prompt": "Create a simple cylinder r=11.0 h=83",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(11.0).extrude(83)"
  },
  {
    "prompt": "Cylinder dia 5, height 98, positioned at (-12, -11)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(2.5).extrude(98).translate((-12, -11, 0))"
  },
  {
    "prompt": "Vertical rod diameter 27 length 76",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(13.5).extrude(76)"
  },
  {
    "prompt": "Cylinder dia 17, height 72, positioned at (-24, -5)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(8.5).extrude(72).translate((-24, -5, 0))"
  },
  {
    "prompt": "Cylinder with diameter 19 and height 72",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(9.5).extrude(72)"
  },
  {
    "prompt": "Vertical rod diameter 47 length 28",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(23.5).extrude(28)"
  },
  {
    "prompt": "Cylinder with diameter 41 and height 49",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(20.5).extrude(49)"
  },
  {
    "prompt": "A 77mm tall cylinder with radius 15.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(15.5).extrude(77)"
  },
  {
    "prompt": "Create a simple cylinder r=7.5 h=17",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(7.5).extrude(17)"
  },
  {
    "prompt": "Vertical rod diameter 21 length 47",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(10.5).extrude(47)"
  },
  {
    "prompt": "Cylinder dia 5, height 68, positioned at (-21, -46)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(2.5).extrude(68).translate((-21, -46, 0))"
  },
  {
    "prompt": "A 29mm tall cylinder with radius 7.0",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(7.0).extrude(29)"
  },
  {
    "prompt": "A 39mm tall cylinder with radius 21.0",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(21.0).extrude(39)"
  },
  {
    "prompt": "Cylinder dia 10, height 34, positioned at (-5, -43)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(5.0).extrude(34).translate((-5, -43, 0))"
  },
  {
    "prompt": "A 32mm tall cylinder with radius 13.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(13.5).extrude(32)"
  },
  {
    "prompt": "Cylinder dia 37, height 56, positioned at (-36, 41)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(18.5).extrude(56).translate((-36, 41, 0))"
  },
  {
    "prompt": "Cylinder with diameter 10 and height 39",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(5.0).extrude(39)"
  },
  {
    "prompt": "Cylinder dia 38, height 67, positioned at (2, 9)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(19.0).extrude(67).translate((2, 9, 0))"
  },
  {
    "prompt": "Cylinder with diameter 16 and height 49",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(8.0).extrude(49)"
  },
  {
    "prompt": "Cylinder with diameter 5 and height 69",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(2.5).extrude(69)"
  },
  {
    "prompt": "A 97mm tall cylinder with radius 18.0",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(18.0).extrude(97)"
  },
  {
    "prompt": "Cylinder dia 20, height 94, positioned at (-26, -16)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(10.0).extrude(94).translate((-26, -16, 0))"
  },
  {
    "prompt": "Cylinder dia 7, height 52, positioned at (8, -23)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(3.5).extrude(52).translate((8, -23, 0))"
  },
  {
    "prompt": "Create a simple cylinder r=19.5 h=47",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(19.5).extrude(47)"
  },
  {
    "prompt": "A 61mm tall cylinder with radius 22.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(22.5).extrude(61)"
  },
  {
    "prompt": "Vertical rod diameter 48 length 65",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(24.0).extrude(65)"
  },
  {
    "prompt": "A 87mm tall cylinder with radius 6.0",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(6.0).extrude(87)"
  },
  {
    "prompt": "Cylinder with diameter 19 and height 44",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(9.5).extrude(44)"
  },
  {
    "prompt": "Create a simple cylinder r=23.5 h=86",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(23.5).extrude(86)"
  },
  {
    "prompt": "A 58mm tall cylinder with radius 17.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(17.5).extrude(58)"
  },
  {
    "prompt": "A 87mm tall cylinder with radius 17.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(17.5).extrude(87)"
  },
  {
    "prompt": "Create a simple cylinder r=6.0 h=81",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(6.0).extrude(81)"
  },
  {
    "prompt": "Cylinder dia 10, height 27, positioned at (-8, -17)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(5.0).extrude(27).translate((-8, -17, 0))"
  },
  {
    "prompt": "Create a simple cylinder r=22.0 h=87",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(22.0).extrude(87)"
  },
  {
    "prompt": "A 91mm tall cylinder with radius 17.0",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(17.0).extrude(91)"
  },
  {
    "prompt": "Cylinder with diameter 15 and height 62",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(7.5).extrude(62)"
  },
  {
    "prompt": "Vertical rod diameter 46 length 84",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(23.0).extrude(84)"
  },
  {
    "prompt": "Vertical rod diameter 44 length 17",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(22.0).extrude(17)"
  },
  {
    "prompt": "Vertical rod diameter 11 length 90",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(5.5).extrude(90)"
  },
  {
    "prompt": "Cylinder with diameter 16 and height 57",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(8.0).extrude(57)"
  },
  {
    "prompt": "Cylinder dia 19, height 83, positioned at (29, 30)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(9.5).extrude(83).translate((29, 30, 0))"
  },
  {
    "prompt": "A 37mm tall cylinder with radius 19.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(19.5).extrude(37)"
  },
  {
    "prompt": "Cylinder with diameter 27 and height 45",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(13.5).extrude(45)"
  },
  {
    "prompt": "Cylinder dia 41, height 69, positioned at (-8, -6)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(20.5).extrude(69).translate((-8, -6, 0))"
  },
  {
    "prompt": "Cylinder dia 16, height 22, positioned at (44, -26)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(8.0).extrude(22).translate((44, -26, 0))"
  },
  {
    "prompt": "A 33mm tall cylinder with radius 24.0",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(24.0).extrude(33)"
  },
  {
    "prompt": "Create a simple cylinder r=20.0 h=57",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(20.0).extrude(57)"
  },
  {
    "prompt": "Cylinder dia 43, height 79, positioned at (19, -21)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(21.5).extrude(79).translate((19, -21, 0))"
  },
  {
    "prompt": "Vertical rod diameter 23 length 96",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(11.5).extrude(96)"
  },
  {
    "prompt": "Cylinder with diameter 46 and height 89",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(23.0).extrude(89)"
  },
  {
    "prompt": "Cylinder dia 35, height 84, positioned at (37, -18)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(17.5).extrude(84).translate((37, -18, 0))"
  },
  {
    "prompt": "Cylinder with diameter 42 and height 77",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(21.0).extrude(77)"
  },
  {
    "prompt": "A 41mm tall cylinder with radius 8.0",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(8.0).extrude(41)"
  },
  {
    "prompt": "A 70mm tall cylinder with radius 7.0",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(7.0).extrude(70)"
  },
  {
    "prompt": "Create a simple cylinder r=14.0 h=33",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(14.0).extrude(33)"
  },
  {
    "prompt": "Cylinder with diameter 43 and height 79",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(21.5).extrude(79)"
  },
  {
    "prompt": "Cylinder with diameter 11 and height 87",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(5.5).extrude(87)"
  },
  {
    "prompt": "Cylinder with diameter 5 and height 61",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(2.5).extrude(61)"
  },
  {
    "prompt": "A 51mm tall cylinder with radius 23.0",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(23.0).extrude(51)"
  },
  {
    "prompt": "Cylinder dia 24, height 41, positioned at (43, -50)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(12.0).extrude(41).translate((43, -50, 0))"
  },
  {
    "prompt": "A 72mm tall cylinder with radius 10.0",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(10.0).extrude(72)"
  },
  {
    "prompt": "Cylinder dia 11, height 41, positioned at (39, -27)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(5.5).extrude(41).translate((39, -27, 0))"
  },
  {
    "prompt": "Cylinder dia 41, height 47, positioned at (48, 33)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(20.5).extrude(47).translate((48, 33, 0))"
  },
  {
    "prompt": "Vertical rod diameter 24 length 47",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(12.0).extrude(47)"
  },
  {
    "prompt": "A 29mm tall cylinder with radius 11.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(11.5).extrude(29)"
  },
  {
    "prompt": "Cylinder dia 28, height 48, positioned at (4, 26)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(14.0).extrude(48).translate((4, 26, 0))"
  },
  {
    "prompt": "Create a simple cylinder r=6.5 h=48",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(6.5).extrude(48)"
  },
  {
    "prompt": "A 52mm tall cylinder with radius 19.0",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(19.0).extrude(52)"
  },
  {
    "prompt": "Cylinder dia 45, height 81, positioned at (13, 31)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(22.5).extrude(81).translate((13, 31, 0))"
  },
  {
    "prompt": "Create a simple cylinder r=8.0 h=35",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(8.0).extrude(35)"
  },
  {
    "prompt": "Cylinder with diameter 8 and height 14",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(4.0).extrude(14)"
  },
  {
    "prompt": "Vertical rod diameter 29 length 51",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(14.5).extrude(51)"
  },
  {
    "prompt": "Create a simple cylinder r=18.5 h=17",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(18.5).extrude(17)"
  },
  {
    "prompt": "Vertical rod diameter 10 length 35",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(5.0).extrude(35)"
  },
  {
    "prompt": "Cylinder dia 47, height 48, positioned at (-42, 15)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(23.5).extrude(48).translate((-42, 15, 0))"
  },
  {
    "prompt": "A 22mm tall cylinder with radius 14.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(14.5).extrude(22)"
  },
  {
    "prompt": "Cylinder with diameter 29 and height 19",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(14.5).extrude(19)"
  },
  {
    "prompt": "Create a simple cylinder r=25.0 h=38",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(25.0).extrude(38)"
  },
  {
    "prompt": "A 67mm tall cylinder with radius 20.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(20.5).extrude(67)"
  },
  {
    "prompt": "A 72mm tall cylinder with radius 18.0",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(18.0).extrude(72)"
  },
  {
    "prompt": "Cylinder with diameter 25 and height 35",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(12.5).extrude(35)"
  },
  {
    "prompt": "Vertical rod diameter 43 length 46",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(21.5).extrude(46)"
  },
  {
    "prompt": "Cylinder dia 19, height 84, positioned at (-7, 31)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(9.5).extrude(84).translate((-7, 31, 0))"
  },
  {
    "prompt": "Create a simple cylinder r=5.0 h=81",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(5.0).extrude(81)"
  },
  {
    "prompt": "Vertical rod diameter 37 length 68",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(18.5).extrude(68)"
  },
  {
    "prompt": "Vertical rod diameter 21 length 94",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').circle(10.5).extrude(94)"
  },
  {
    "prompt": "A 32mm diameter sphere",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(16.0)"
  },
  {
    "prompt": "A 44mm diameter sphere",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(22.0)"
  },
  {
    "prompt": "Create a sphere of size 14.5 positioned at origin",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(14.5)"
  },
  {
    "prompt": "Sphere with radius 10.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(10.5)"
  },
  {
    "prompt": "Sphere with radius 2.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(2.5)"
  },
  {
    "prompt": "Ball with diameter 39",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(19.5)"
  },
  {
    "prompt": "A 14mm diameter sphere",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(7.0)"
  },
  {
    "prompt": "Sphere r=16.0 at (2, 4, 15)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(16.0).translate((2, 4, 15))"
  },
  {
    "prompt": "Sphere with radius 9.0",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(9.0)"
  },
  {
    "prompt": "Sphere r=17.5 at (-14, 7, 10)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(17.5).translate((-14, 7, 10))"
  },
  {
    "prompt": "A 9mm diameter sphere",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(4.5)"
  },
  {
    "prompt": "Sphere with radius 9.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(9.5)"
  },
  {
    "prompt": "Sphere with radius 19.0",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(19.0)"
  },
  {
    "prompt": "Ball with diameter 27",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(13.5)"
  },
  {
    "prompt": "Sphere r=15.5 at (7, -1, 14)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(15.5).translate((7, -1, 14))"
  },
  {
    "prompt": "Ball with diameter 42",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(21.0)"
  },
  {
    "prompt": "Ball with diameter 38",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(19.0)"
  },
  {
    "prompt": "Ball with diameter 33",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(16.5)"
  },
  {
    "prompt": "Create a sphere of size 9.5 positioned at origin",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(9.5)"
  },
  {
    "prompt": "A 37mm diameter sphere",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(18.5)"
  },
  {
    "prompt": "Sphere r=4.5 at (17, -16, 6)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(4.5).translate((17, -16, 6))"
  },
  {
    "prompt": "Sphere r=17.0 at (7, -3, 11)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(17.0).translate((7, -3, 11))"
  },
  {
    "prompt": "Sphere r=9.0 at (-17, 10, 1)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(9.0).translate((-17, 10, 1))"
  },
  {
    "prompt": "Create a sphere of size 12.0 positioned at origin",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(12.0)"
  },
  {
    "prompt": "Sphere r=18.0 at (-18, 14, 13)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(18.0).translate((-18, 14, 13))"
  },
  {
    "prompt": "Sphere r=20.0 at (-4, -2, 1)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(20.0).translate((-4, -2, 1))"
  },
  {
    "prompt": "Sphere with radius 21.0",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(21.0)"
  },
  {
    "prompt": "Ball with diameter 45",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(22.5)"
  },
  {
    "prompt": "Sphere r=12.0 at (-2, 7, 17)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(12.0).translate((-2, 7, 17))"
  },
  {
    "prompt": "Sphere with radius 4.0",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(4.0)"
  },
  {
    "prompt": "Ball with diameter 29",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(14.5)"
  },
  {
    "prompt": "A 33mm diameter sphere",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(16.5)"
  },
  {
    "prompt": "Ball with diameter 32",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(16.0)"
  },
  {
    "prompt": "Sphere with radius 23.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(23.5)"
  },
  {
    "prompt": "Sphere r=15.5 at (2, 1, 9)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(15.5).translate((2, 1, 9))"
  },
  {
    "prompt": "Sphere with radius 12.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(12.5)"
  },
  {
    "prompt": "A 8mm diameter sphere",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(4.0)"
  },
  {
    "prompt": "Create a sphere of size 22.5 positioned at origin",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(22.5)"
  },
  {
    "prompt": "Ball with diameter 39",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(19.5)"
  },
  {
    "prompt": "Ball with diameter 34",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(17.0)"
  },
  {
    "prompt": "Create a sphere of size 12.5 positioned at origin",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(12.5)"
  },
  {
    "prompt": "Sphere r=9.5 at (-15, 16, 8)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(9.5).translate((-15, 16, 8))"
  },
  {
    "prompt": "Sphere with radius 19.0",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(19.0)"
  },
  {
    "prompt": "Ball with diameter 43",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(21.5)"
  },
  {
    "prompt": "Create a sphere of size 12.5 positioned at origin",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(12.5)"
  },
  {
    "prompt": "Sphere with radius 18.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(18.5)"
  },
  {
    "prompt": "Sphere r=7.5 at (11, -7, 5)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(7.5).translate((11, -7, 5))"
  },
  {
    "prompt": "Ball with diameter 9",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(4.5)"
  },
  {
    "prompt": "Create a sphere of size 15.0 positioned at origin",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(15.0)"
  },
  {
    "prompt": "Sphere with radius 8.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(8.5)"
  },
  {
    "prompt": "Create a sphere of size 21.5 positioned at origin",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(21.5)"
  },
  {
    "prompt": "Sphere with radius 21.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(21.5)"
  },
  {
    "prompt": "Create a sphere of size 21.0 positioned at origin",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(21.0)"
  },
  {
    "prompt": "A 26mm diameter sphere",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(13.0)"
  },
  {
    "prompt": "Create a sphere of size 6.0 positioned at origin",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(6.0)"
  },
  {
    "prompt": "Ball with diameter 48",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(24.0)"
  },
  {
    "prompt": "Sphere r=2.5 at (-1, 16, 3)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(2.5).translate((-1, 16, 3))"
  },
  {
    "prompt": "Create a sphere of size 19.0 positioned at origin",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(19.0)"
  },
  {
    "prompt": "Ball with diameter 22",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(11.0)"
  },
  {
    "prompt": "Sphere r=3.5 at (18, -11, 4)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(3.5).translate((18, -11, 4))"
  },
  {
    "prompt": "Ball with diameter 35",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(17.5)"
  },
  {
    "prompt": "A 42mm diameter sphere",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(21.0)"
  },
  {
    "prompt": "Ball with diameter 49",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(24.5)"
  },
  {
    "prompt": "Sphere with radius 23.0",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(23.0)"
  },
  {
    "prompt": "Create a sphere of size 10.0 positioned at origin",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(10.0)"
  },
  {
    "prompt": "Create a sphere of size 12.0 positioned at origin",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(12.0)"
  },
  {
    "prompt": "Sphere with radius 17.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(17.5)"
  },
  {
    "prompt": "Ball with diameter 40",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(20.0)"
  },
  {
    "prompt": "Create a sphere of size 4.5 positioned at origin",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(4.5)"
  },
  {
    "prompt": "Ball with diameter 16",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(8.0)"
  },
  {
    "prompt": "A 48mm diameter sphere",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(24.0)"
  },
  {
    "prompt": "A 39mm diameter sphere",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(19.5)"
  },
  {
    "prompt": "Sphere with radius 3.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(3.5)"
  },
  {
    "prompt": "A 47mm diameter sphere",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(23.5)"
  },
  {
    "prompt": "Sphere r=21.5 at (19, -18, 0)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(21.5).translate((19, -18, 0))"
  },
  {
    "prompt": "Ball with diameter 23",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(11.5)"
  },
  {
    "prompt": "Sphere with radius 7.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(7.5)"
  },
  {
    "prompt": "Ball with diameter 15",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(7.5)"
  },
  {
    "prompt": "A 7mm diameter sphere",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(3.5)"
  },
  {
    "prompt": "Sphere r=8.5 at (2, 9, 3)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(8.5).translate((2, 9, 3))"
  },
  {
    "prompt": "Ball with diameter 19",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(9.5)"
  },
  {
    "prompt": "Create a sphere of size 13.0 positioned at origin",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(13.0)"
  },
  {
    "prompt": "Sphere r=20.5 at (-20, -3, 3)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(20.5).translate((-20, -3, 3))"
  },
  {
    "prompt": "A 22mm diameter sphere",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(11.0)"
  },
  {
    "prompt": "Sphere r=5.0 at (6, -14, 3)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(5.0).translate((6, -14, 3))"
  },
  {
    "prompt": "Ball with diameter 46",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(23.0)"
  },
  {
    "prompt": "A 38mm diameter sphere",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(19.0)"
  },
  {
    "prompt": "Create a sphere of size 16.5 positioned at origin",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(16.5)"
  },
  {
    "prompt": "Sphere with radius 14.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(14.5)"
  },
  {
    "prompt": "Sphere r=12.5 at (-9, 1, 7)",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(12.5).translate((-9, 1, 7))"
  },
  {
    "prompt": "Create a sphere of size 10.0 positioned at origin",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(10.0)"
  },
  {
    "prompt": "Create a sphere of size 2.5 positioned at origin",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(2.5)"
  },
  {
    "prompt": "Sphere with radius 10.0",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(10.0)"
  },
  {
    "prompt": "Create a sphere of size 13.0 positioned at origin",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(13.0)"
  },
  {
    "prompt": "Create a sphere of size 18.0 positioned at origin",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(18.0)"
  },
  {
    "prompt": "Sphere with radius 2.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(2.5)"
  },
  {
    "prompt": "Sphere with radius 7.5",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(7.5)"
  },
  {
    "prompt": "Create a sphere of size 23.5 positioned at origin",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(23.5)"
  },
  {
    "prompt": "Ball with diameter 31",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(15.5)"
  },
  {
    "prompt": "A 22mm diameter sphere",
    "code": "import cadquery as cq\nresult = cq.Workplane('XY').sphere(11.0)"
  }
]